update url

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -8,31 +8,22 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=./lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
-
-install_aria2() {
+install_git_worktree_wrapper() {
   local install_type=$1
   local version=$2
   local install_path=$3
 
   if [ "$install_type" != "version" ]; then
-    fail "asdf-aria2 supports release installs only"
+    fail "asdf-git-worktree-wrapper only supports release installs only"
   fi
 
-  local download_url
-
-  case "$OSTYPE" in
-    darwin*) download_url="https://github.com/aria2/aria2/releases/download/release-${version}/aria2-${version}-osx-darwin.tar.bz2" ;;
-    linux*) download_url="https://github.com/aria2/aria2/releases/download/release-${version}/aria2-${version}.tar.bz2" ;;
-    *) fail "Unsupported platform" ;;
-  esac
-
-  local source_path="${install_path}/bin/aria2.tar.bz2"
+  local download_url="https://github.com/lu0/git-worktree-wrapper/archive/refs/tags/v${version}.tar.gz" ;;
+  local source_path="${install_path}/bin/git-worktree-wrapper.tar.gz"
 
   (
-    echo "∗ Downloading and installing aria2..."
+    echo "∗ Downloading and installing git-worktree-wrapper..."
     curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
-    tar -xjf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
+    tar -xf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
     echo "The installation was successful!"
     rm "$source_path"
   ) || (
@@ -41,4 +32,4 @@ install_aria2() {
   )
 }
 
-install_aria2 "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_git_worktree_wrapper "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
